name: eduction_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  chewie: ^1.7.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  file_picker: ^5.3.1
  get_it: ^7.6.0
  iconly: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.3.2
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.1.11
  video_thumbnail: ^0.5.3
  youtube_metadata: ^1.0.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.3
  firebase_ui_auth: ^1.7.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  mockito: ^5.4.0
  bloc_test: ^9.1.5
  fake_cloud_firestore: ^2.4.4
  flutter_lints: ^2.0.0
  firebase_auth_mocks: ^0.13.0
  firebase_storage_mocks: ^0.6.1
  very_good_analysis: ^4.0.0+1
  google_sign_in_mocks: ^0.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/vectors/
    - assets/lottie_jsons/
    - assets/images/


fonts:
  - family: Beautiful-people-font
    fonts:
      - asset: assets/fonts/beautiful-people-font/BeautifulPeoplePersonalUse-dE0g.ttf
  - family: Agbalumo
    fonts:
      - asset: assets/fonts/Agbalumo/Agbalumo-Regular.ttf
  - family: Bite-chocolate-font
    fonts:
      - asset: assets/fonts/bite-chocolate-font/BiteChocolate-2RGl.ttf
  - family: Snowburst_One
    fonts:
      - asset: assets/fonts/Snowburst_One/SnowburstOne-Regular.ttf
