// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARTmljfDRR6Xwhm9QhpN4z8FTJHR1pimY',
    appId: '1:38324307438:web:e53b3071924548c1d1baff',
    messagingSenderId: '38324307438',
    projectId: 'livetest2-e3dcc',
    authDomain: 'livetest2-e3dcc.firebaseapp.com',
    storageBucket: 'livetest2-e3dcc.appspot.com',
    measurementId: 'G-NBNZZ7QTCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGw9oqA0Xhzmsj3U30RAAsKEgSsctpC5M',
    appId: '1:38324307438:android:dd5080d480d78efbd1baff',
    messagingSenderId: '38324307438',
    projectId: 'livetest2-e3dcc',
    storageBucket: 'livetest2-e3dcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGxUcq5ub4HEXDlXxB7WG4l1NSGL09i4',
    appId: '1:38324307438:ios:4ee0066d9ebbc296d1baff',
    messagingSenderId: '38324307438',
    projectId: 'livetest2-e3dcc',
    storageBucket: 'livetest2-e3dcc.appspot.com',
    iosBundleId: 'com.example.eductionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGxUcq5ub4HEXDlXxB7WG4l1NSGL09i4',
    appId: '1:38324307438:ios:4ee0066d9ebbc296d1baff',
    messagingSenderId: '38324307438',
    projectId: 'livetest2-e3dcc',
    storageBucket: 'livetest2-e3dcc.appspot.com',
    iosBundleId: 'com.example.eductionApp',
  );
}
